remote_theme: jekyll/minima@2.5.2

title: System Design Resources

author:
  name: Abhishek Arya
  email: abhishekarya102@gmail.com

minima:
  skin: auto
  nav_pages:
    - HLD.md
    - LLD.md

plugins:
  - jekyll-seo-tag
